---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2019/10/13 10:24
---
DDX = {}
function DDX:Say(str)
    Output(str)
end

function DDX.Test()
    DDX:Say("123")
    DDX.Say(self, "456")
end